version: '3'

services:
  redis:
    image: "library/redis:alpine"
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "6380:6379"
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./data/redis/:/data/
      - ./log/redis/:/var/log/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
  mysql:
    image: mysql:5.7
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql/:/var/lib/mysql/
      - ./data/init/:/docker-entrypoint-initdb.d/
      - ./log/mysql/:/var/log/mysql/
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    restart: always
  rollup_springboot:
    build:
      context: Java/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9091:9091"
    volumes:
      - ./log/rollup/:/log/
      - ./data/previewPdf/:/previewPdf/
      - ./data/video/:/video/
    depends_on:
      - redis
      - mysql
    restart: always
  rollup_web:
    build:
      context: Web/
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "9092:80"
    depends_on:
      - rollup_springboot
    restart: always